// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
// const sidebars = {
//   // By default, Docusaurus generates a sidebar from the docs folder structure
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

//   // But you can create a sidebar manually
//   /*
//   tutorialSidebar: [
//     'intro',
//     'hello',
//     {
//       type: 'category',
//       label: 'Tutorial',
//       items: ['tutorial-basics/create-a-document'],
//     },
//   ],
//    */
// };
const sidebars = {
  tutorialSidebar: [
    'chapter-01-ai-native-development',
    'chapter-02-spec-driven-workflows',
    'chapter-03-using-spec-kit-plus',
    'chapter-04-human-in-the-loop-collaboration',
    'chapter-05-practical-examples-and-case-studies',
    'chapter-06-best-practices-and-patterns',
    'chapter-07-troubleshooting-and-common-pitfalls',
    'chapter-08-future-of-ai-native-development',
    'appendix-practical-reference',
  ],
};

module.exports = sidebars;
export default sidebars;
